### ISSUE TITLE
Add Davis Tech Icon Favicon.

### ISSUE THREAD

**Issue by GeorgeRay** [Davis-Technical-College/CanvasAssistantBlazorWASM#22]

**Comment by brandinonian** [comment]
Done

**Comment by GeorgeRay** [comment]
It favicon is still the Blazor favicon.

**Comment by AndiMontag** [comment]
Favicon file needed to end in .ico, not .png, fixed.

**Comment by GeorgeRay** [comment]
Will you create a pull request for the fix?

**Comment by AndiMontag** [comment]
Created, it's combined with the course pagination pull request I believe.

**Comment by GeorgeRay** [comment]
Looks good.
